version: '3'
services:
    mongodb:
        image: mongo
        volumes:
            - mongodb_data:/data/db
        ports:
            - 27017:27017

    redis:
        image: redis
        ports:
            - "6379:6379"
  
volumes:
    mongodb_data:
        driver: local